# Production environment configuration

# Server configuration
server:
  port: 8080
spring:
  application:
    name: stripe-lunar
  
  # Oracle Database Configuration
  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@//db:1521/XEPDB1}
    username: ${DB_USERNAME:stripe_lunar}
    password: ${DB_PASSWORD:password}
    driver-class-name: oracle.jdbc.OracleDriver
  
  # JPA/Hibernate
  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: STRIPE_LUNAR
  
  # Flyway configuration
  flyway:
    baseline-on-migrate: true
    schemas: STRIPE_LUNAR
    create-schemas: true
    default-schema: STRIPE_LUNAR
  
  # Security
  security:
    user:
      name: ${ADMIN_USERNAME:admin}
      password: ${ADMIN_PASSWORD:admin}

# Stripe API configuration
stripe:
  api:
    key: ${STRIPE_API_KEY}
  webhook:
    secret: ${STRIPE_WEBHOOK_SECRET}

# Camel properties
camel:
  springboot:
    name: StripeLunarETL
  servlet:
    mapping:
      context-path: /api/*
  component:
    servlet:
      binding-mode: json

# Logging
logging:
  level:
    root: WARN
    org:
      apache:
        camel: INFO
    com:
      lunar:
        stripelunar: INFO

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized

# Swagger
springdoc:
  swagger-ui:
    enabled: false
